### ISSUE TITLE
Not showed mempool transactions and a receive button doesn't work with bitcoin on-chain addresses

### ISSUE THREAD

**Issue by Perlover** [nbd-wtf/obw#1]
Hello!

I installed v0.1.4 first time and sent to bitcoin address some funds. But after this I don't see any transaction. I think your wallet doesn't show mempool transactions. Right? For example the SBW shows any transactions - mempool and blockchain ones. And other difference against the SBW wallet - when I press the Receive button I cannot choose bitcoin method. I see warning that I don't have LN channels. Both of these moments are confusing...

**Comment by fiatjaf** [comment]
It should definitely should show mempool transactions, a bug may have occurred.

**Comment by Perlover** [comment]
Moreover, I then opened (outbound) a channel (from not-confirmed) UTXO, then I was able to open another channel (outbound) from these UTXOs, and then I already executed a transaction through Electrum (I imported the seed there - I did this because I was confused by two open channels from one UTXO). And all through one UTXO.

**Comment by Perlover** [comment]
And after the Electrum's transaction was confirmed I run the OBW and got a error window from there with logs:

```
java.lang.IllegalStateException: Promise already completed.
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.failure(Promise.scala:109)
	at scala.concurrent.Promise.failure$(Promise.scala:109)
	at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:104)
	at fr.acinq.eclair.blockchain.electrum.ElectrumClient.$anonfun$shutdown$2(ElectrumClient.scala:546)
	at fr.acinq.eclair.blockchain.electrum.-$$Lambda$oD9tOEyAJE8QbpNB1IlJEw0fo1U.apply(Unknown Source:2)
	at scala.collection.mutable.HashMap$Node.foreach(HashMap.scala:627)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:489)
	at fr.acinq.eclair.blockchain.electrum.ElectrumClient.shutdown(ElectrumClient.scala:545)
	at fr.acinq.eclair.blockchain.electrum.ElectrumClientPool.killClient(ElectrumClientPool.scala:80)
	at fr.acinq.eclair.blockchain.electrum.ElectrumClient$$anon$1$$anon$2.run(ElectrumClient.scala:529)
	at java.util.TimerThread.mainLoop(Timer.java:563)
	at java.util.TimerThread.run(Timer.java:513)
```

**Comment by Perlover** [comment]
> It should definitely should show mempool transactions, a bug may have occurred.

May be because I use my own electrs electrum server but use the same server with SBW and don't have problems.

**Comment by fiatjaf** [comment]
I'm actively debugging this right now. If you want to contact me at https://t.me/fiatjaf for  quicker help please do that (otherwise I'll give you news when I have them here).

**Comment by fiatjaf** [comment]
Fixed some bugs here: https://github.com/nbd-wtf/obw/releases/tag/v0.1.5

You might have to delete the app data and start anew to make sure everything is in sync (don't do it if you have normal channels).

**Comment by fiatjaf** [comment]
I think this might be fixed, I'll close it for now, but if it's not fixed please reopen it.
