### ISSUE TITLE
lnurl withdrawRequest makes OBW crashes

### ISSUE THREAD

**Issue by Bashy** [nbd-wtf/obw#11]
OBW v0.1.6

When a `withdrawRequest` is being processed right after step 6 on [LUD-03](https://github.com/fiatjaf/lnurl-rfc/blob/luds/03.md))
OBW crashes and unexpectly closes.

I tried with lnbits (withdraw extension) and another custom implementation of `withdrawRequest` `LN SERVICE`, others wallets (Pheonix, SBW, Blue Wallet, LNBits itself) don't have this problem.

When we open OBW again, we can see the invoice has been created, but is not paid.

On the `LN SERVICE` side, all steps are done and `{"status": "OK"}` is sent, but the invoice is never claimed (not sure about the vocabulary here).

LNBits withdraw extension confirms that the invoice has been processed (callback http get is also done).

```
10-30 10:59:31.846   966  2620 D MdnieScenarioControlService:  packageName : wtf.nbd.obw    className : wtf.nbd.obw.EmergencyActivity
10-30 10:59:31.847   966  2620 V MdnieScenarioControlService: setUIMode from UI function(3)
10-30 10:59:31.850 27714 27739 I libEGL  : EGL_ANDROID_blob_cache_path advertised, but unable to get eglSetBlobCachePathANDROID
10-30 10:59:31.857 27714 27739 D OpenGLRenderer: RenderThread::setGrContext()
10-30 10:59:31.864 27714 27714 I DecorView: [INFO] isPopOver=false, config=true
10-30 10:59:31.864 27714 27714 I DecorView: updateCaptionType >> DecorView@d6b233a[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
10-30 10:59:31.864 27714 27714 D DecorView: setCaptionType = 0, this = DecorView@d6b233a[]
10-30 10:59:31.865 27714 27714 I DecorView: getCurrentDensityDpi: from real metrics. densityDpi=420 msg=resources_loaded
10-30 10:59:31.885   966   988 D InputTransport: Input channel constructed: '9aa22a8', fd=921
10-30 10:59:31.885   966   988 D InputTransport: Input channel constructed: '9aa22a8', fd=922
10-30 10:59:31.885   966   988 D InputTransport: Input channel constructed: '9aa22a8', fd=925
10-30 10:59:31.888   629  1302 I SurfaceFlinger: id=797280 createSurf (0x0),-1 flag=80004, 9aa22a8 wtf.nbd.obw/wtf.nbd.obw.EmergencyActivity#0
10-30 10:59:31.889   966   988 D RestrictionPolicy: isScreenCaptureEnabled : ret=true userId=0
10-30 10:59:31.889   966   988 D InputTransport: Input channel destroyed: '9aa22a8', fd=925
10-30 10:59:31.893 27714 27714 I ViewRootImpl@be995db[EmergencyActivity]: setView = com.android.internal.policy.DecorView@d6b233a TM=true
10-30 10:59:31.896 27714 27714 D AndroidRuntime: Shutting down VM
10-30 10:59:31.896 27714 27714 E AndroidRuntime: FATAL EXCEPTION: main
10-30 10:59:31.896 27714 27714 E AndroidRuntime: Process: wtf.nbd.obw, PID: 27714
10-30 10:59:31.896 27714 27714 E AndroidRuntime: java.lang.RuntimeException: Unable to start service wtf.nbd.obw.utils.AwaitService@e33e424 with Intent { act=actionShow cmp=wtf.nbd.obw/.utils.AwaitService (has extras) }: java.lang.IllegalArgumentException: wtf.nbd.obw: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
10-30 10:59:31.896 27714 27714 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.app.ActivityThread.access$2200(ActivityThread.java:310)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8663)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
10-30 10:59:31.896 27714 27714 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: wtf.nbd.obw: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
10-30 10:59:31.896 27714 27714 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.app.PendingIntent.getActivity(PendingIntent.java:451)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.app.PendingIntent.getActivity(PendingIntent.java:415)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at wtf.nbd.obw.utils.AwaitService.processServiceIntent(AwaitService.scala:49)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at wtf.nbd.obw.utils.AwaitService.onStartCommand(AwaitService.scala:35)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
10-30 10:59:31.896 27714 27714 E AndroidRuntime:        ... 9 more
```

Android 12
Samsung S10e

**Comment by Bashy** [comment]
Similar to #6

**Comment by Bashy** [comment]
Proposing #12 , hoping that also still works on android version older than 12

**Comment by Darth-Coin** [comment]
I just did the same test, LNURL-w from legend.lnbits.com, scan the QR with OBW 0.1.6 and worked for me.
Android 8.1, LG K10

**Comment by fiatjaf** [comment]
Does #12 fix this for newer Androids? If yes we can close this.

**Comment by Bashy** [comment]
Tested on Android 12, app doesn't crash anymore, but invoice is still not _redeemed_.

**Comment by Bashy** [comment]
Ah maybe needed to wait a bit after creation of the hosted channel, seems to work now!

**Comment by Bashy** [comment]
PR https://github.com/nbd-wtf/obw/pull/12 fixed the issue
