### ISSUE TITLE
Not possible to receive payments from THNDR

### ISSUE THREAD

**Issue by wchancao** [nbd-wtf/obw#2]
I was trying OBW, receiving and sending payments with the Jiraiya HC, and notice that is impossible to receive the micropayments from thndr games... Its weird because its possible to receive them with SBW, WoS, Muun, so the problem is not at their end. 

When i tap OBW on the game to claim the sats, OBW opens but then nothing happens...

**Comment by fiatjaf** [comment]
What do you mean by "impossible"? Is that using lnurl-withdraw? Is it a `lightning:...` link that you click and it opens OBW?

**Comment by wchancao** [comment]
Yes, i guess that thndr use lnurl-withdraw to pay the prizes... I click a button in the game and that brings the wallet app, then in the wallet you accept the payment, it works like that in sbw and wos, muun auto-accepts the payment. But in obw nothing happens..

**Comment by fiatjaf** [comment]
Are you telling me Thundr has a dedicated button for OBW? Or is it a generic lnurl-withdraw link?

If it is a generic lnurl-withdraw link, can you send me one as an example?

**Comment by wchancao** [comment]
Dont know if its a "dedicated" button for obw, it detects all LN wallets installed in the phone... it doesnt give you a link, but i guess its a lnurl link under the hood... This is what i get in sbw, and wos, but not in obw
![IMG_20221020_084504](https://user-images.githubusercontent.com/488773/196953221-0e7fe5d3-05f6-4b63-8a3d-cac983983d5f.jpg)
![Screenshot_2022-10-20-08-50-58-481_com livingroomofsatoshi wallet](https://user-images.githubusercontent.com/488773/196953803-91e1865a-b1cb-4c46-afdc-520658ca2feb.jpg)

**Comment by fiatjaf** [comment]
I can't reproduce that. How do I download that Thundr thing to try? I tried with ln.cash and this was the result:

https://user-images.githubusercontent.com/1653275/197391969-c42bbf04-f266-4c52-bd3a-e01eaa129c7b.mp4

Or maybe you can try to hold your pointer over it and and copy the lnurl-withdraw link you get from Thundr and send it to me so I can take a look? I don't know if that is possible but it's worth a try.

**Comment by wchancao** [comment]
You can install "Club Bitcoin" from the Play Store, play a game, win some sats and try to withdraw them with OBW... Theres no way to copy the lnurl, or i dont know how xD

**Comment by fiatjaf** [comment]
But sir, I don't have Play Store!

**Comment by fiatjaf** [comment]
I've installed this crap, played a game, it showed me a terribly annoying ad and didn't give me any sats. What are the next steps?

**Comment by wchancao** [comment]
Did you get some purple tickets? If you have the tickets you will get sats in an hour...

**Comment by fiatjaf** [comment]
I have 8 purple tickets, call me a Solitaire genius.

**Comment by rafaelpac** [comment]
@jackeveritt

**Comment by jackeveritt** [comment]
The game will open a wallet with lightning://<lnurl withdraw>.  Perhaps it is opening the wallet ok, but the <lnurl withdraw> part is not read for some reason? I can also generate you a LNURL if you want @fiatjaf

**Comment by wchancao** [comment]
Maybe thndr is not paying to wallets that were not installed through the play store? Does that make sense? The game opens OBW ok, but then the wallet does nothing at all...

**Comment by jackeveritt** [comment]
@fiatjaf I dm'd some LNURLs on telegram if they are helpful

**Comment by jackeveritt** [comment]
> Maybe thndr is not paying to wallets that were not installed through the play store? Does that make sense? The game opens OBW ok, but then the wallet does nothing at all...

Supposed to work on any app that supports opening LNURL withdraws via lightning://  should not matter about play store

**Comment by fiatjaf** [comment]
I get this error on the fast-withdraw LNURL:

```
java.lang.NoSuchMethodError: No virtual method flip()Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
 at immortan.utils.uri.UriCodec.flushDecodingByteAccumulator(UriCodec.java:150)
 at immortan.utils.uri.UriCodec.appendDecoded(UriCodec.java:136)
 at immortan.utils.uri.UriCodec.decode(UriCodec.java:71)
 at immortan.utils.uri.Uri.getQueryParameter(Uri.java:1593)
 at immortan.utils.LNUrl.$anonfun$fastWithdrawAttempt$1(LNUrl.scala:110)
 at immortan.utils.-$$Lambda$GjfGyjTqCJra4T455mXl-oBPNzY.apply(Unknown Source:2)
 at scala.util.Try$.apply(Try.scala:210)
 at immortan.utils.LNUrl.fastWithdrawAttempt$lzycompute(LNUrl.scala:107)
 at immortan.utils.LNUrl.fastWithdrawAttempt(LNUrl.scala:107)
 at wtf.nbd.obw.HubActivity$$anonfun$checkExternalData$1.applyOrElse(HubActivity.scala:2350)
 at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
 at immortan.utils.InputParser$.checkAndMaybeErase(InputParser.scala:25)
 at wtf.nbd.obw.HubActivity.checkExternalData(HubActivity.scala:2122)
 at wtf.nbd.obw.HubActivity.$anonfun$bringSendOptions$6(HubActivity.scala:2676)
 at wtf.nbd.obw.HubActivity.$anonfun$bringSendOptions$6$adapted(HubActivity.scala:2673)
 at wtf.nbd.obw.-$$Lambda$fhsmLQJPw2y3G5LYK67g-OfIWkQ.apply(Unknown Source:4)
 at wtf.nbd.obw.BaseActivity.$anonfun$runFutureProcessOnUI$2(BaseActivity.scala:273)
 at wtf.nbd.obw.-$$Lambda$7sLNsOLl1sATbfGX3ztJ04hnydE.apply$mcV$sp(Unknown Source:4)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
 at wtf.nbd.obw.BaseActivity$$anon$6.run(BaseActivity.scala:290)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6626)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by fiatjaf** [comment]
Fixed at https://github.com/nbd-wtf/immortan/commit/63f76b2c4e62663d4ddea88261bd6d6c30f9a57c.
